name = "tagstash"
compatibility_date = "2026-03-31"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "tagstash-db"
database_id = "8ed8b994-49cd-42aa-9175-90c98df15307"
migrations_dir = "d1/migrations"
